"use strict";

const fs = require("fs");

let utils = require("../utils");

// Instruction.cpp
let ethSource = fs.readFileSync("./data/ethereum_source.txt").toString();
let interpreter = false;

utils.parseByLine(ethSource, false).forEach((row) => {
    if(!row) {
        interpreter = false; // we suppose that empty line separates blocks of opcodes
        return;
    }
    if(/generated by the interpreter/.test(row)) {
        interpreter = true;
        return;
    }

    let rawData = row.replace(/^{/, "").split("{")[1].replace(" } }", "").split(",").map(str => str.trim());
    let data = [
        JSON.parse(rawData[0]),
        Number(rawData[1]),
        Number(rawData[2]),
        rawData[3].replace("Tier::", ""),
    ];

    let jsonData = {
        mnemonic: data[0],
        pops: data[1],
        pushes: data[2],
        tier: data[3],
    };
    if(interpreter) {
        jsonData.internal = true;
    }

    let opcode = utils.findOpcodeByName(jsonData.mnemonic);
    if(utils.isEmpty(opcode)) {
        jsonData.tentative = true;
    }

    utils.extend(opcode, jsonData);
});

utils.saveCommon();
